### ISSUE TITLE
Picture Not Showing On Website. Why?

### ISSUE THREAD

**Issue by bell-kevin** [bell-kevin/Kevin-Bell#4]
Picture shows up on READme website, but Not Showing On actual Website. Why? Any help is appreciated.

**Comment by GeorgeRay** [comment]
Hi, Kevin. The server GitHub uses for github.io is case-sensitive. You have uppercase PNG in the file name and lowercase in the code. Make them match, and your pic will show up.

**Comment by bell-kevin** [comment]
Thank you!

**Comment by bell-kevin** [comment]
It's still not working. Why?

**Comment by GeorgeRay** [comment]
what is the URL that it is not showing up on?

**Comment by bell-kevin** [comment]
[bellKevin.me](https://bellkevin.me/)

**Comment by GeorgeRay** [comment]
It might have to be with how you have the file named.

https://tomcam.github.io/least-github-pages/adding-images-github-pages-site.html
Adding images to your GitHub Pages site<https://tomcam.github.io/least-github-pages/adding-images-github-pages-site.html>
Adding images to your GitHub Pages site. The Jekyll publishing system used by GitHub Pages expects you to have an assets directory, and that’s where image files should be placed. By convention they go into an images subdirectory (full path /docs/assets/images but that’s not a firm requirement. They can be anywhere in the /docs/assets path.. Create a directory called /docs/assets
tomcam.github.io

https://github.com/orgs/community/discussions/23086
[https://opengraph.githubassets.com/6bbb29fdc48a648fb80597fa35c7d4d7aabc46f5eedf5584c6024b2808b6a572/orgs/community/discussions/23086]<https://github.com/orgs/community/discussions/23086>
Github pages' images not working · Discussion #23086 · community<https://github.com/orgs/community/discussions/23086>
I am still new to github pages overall and started playing with some items by creating an item through VScode CLI. I have read online that GitHub pages is case sensitive and even after double-check...
github.com


________________________________

**Comment by bell-kevin** [comment]
We'll see if this works.

[https://github.com/bell-kevin/Kevin-Bell/blob/main/docs/assets/img/bellKevin.png](https://github.com/bell-kevin/Kevin-Bell/blob/main/docs/assets/img/bellKevin.png)

**Comment by bell-kevin** [comment]
Still not working...

**Comment by bell-kevin** [comment]
Still not working...

**Comment by GeorgeRay** [comment]
https://stackoverflow.com/questions/48919200/github-pages-only-showing-readme-file

https://stackoverflow.com/questions/17141612/images-in-github-pages-and-relative-links
________________________________

**Comment by bell-kevin** [comment]
Got it!

**Comment by BlocBoiMonzer** [comment]
@bell-kevin did you figure it out? None of the solutions about case sensitivity and path applied to me. Haven't tried the full path tho

**Comment by bell-kevin** [comment]
Yes!

This did the trick:

<img src="https://raw.githubusercontent.com/bell-kevin/Kevin-Bell/main/kevinBell.png" alt="Kevin" class="inline"/>

And again this was from: 

https://raw.githubusercontent.com/bell-kevin/Kevin-Bell/main/README.md

**Comment by bell-kevin** [comment]
@BlocBoiMonzer email me if you need more help. bellKevin@pm.me

**Comment by BlocBoiMonzer** [comment]
Thank you Kevin @bell-kevin . So basically, you used a URL to link the images?

**Comment by bell-kevin** [comment]
"<img src="https://raw.githubusercontent.com/bell-kevin/Kevin-Bell/main/kevinBell.png" alt="Kevin" class="inline"/>" Not in double quotes. Starting with < and ending with >. That did the trick for me.

**Comment by BlocBoiMonzer** [comment]
Thanks good sir

**Comment by bell-kevin** [comment]
@BlocBoiMonzer You're welcome!
